/* Generated by firmware-agent from smart-kettle.fw.json and bard cues.json; do not edit. */
#ifndef FW_CUES_H
#define FW_CUES_H

#include <stdint.h>

#define FW_CUES_PRODUCT "smart-kettle"
#define FW_CUES_DEVICE "piezo"
#define FW_CUES_SOURCE_SHA256 "b34773f9e0af18dc37fea604d3fdd7315fd29450920df52990de2ab180f3eadd"
#define FW_CUES_PIN FW_PIN_BUZZER
#define FW_CUES_MIN_CENTIHZ 50000u
#define FW_CUES_MAX_CENTIHZ 500000u
#define FW_CUE_COUNT 4

typedef struct {
    uint32_t centihz;
    uint16_t duration_ms;
} fw_cue_tone_t;

typedef struct {
    const fw_cue_tone_t *tones;
    uint16_t tone_count;
    uint16_t duration_ms;
    uint8_t loop;
} fw_cue_t;

#define FW_CUE_BOOT 0 /* startup */
#define FW_CUE_DONE 1 /* completion */
#define FW_CUE_OVERHEAT 2 /* warning */
#define FW_CUE_PRESS 3 /* confirm */

static const fw_cue_tone_t fw_cue_boot_tones[] = {{104650u, 83u}, {131851u, 84u}, {156798u, 166u}};
static const fw_cue_tone_t fw_cue_done_tones[] = {{156798u, 200u}, {209300u, 400u}};
static const fw_cue_tone_t fw_cue_overheat_tones[] = {{176000u, 125u}, {0u, 125u}, {176000u, 125u}, {0u, 125u}, {176000u, 250u}};
static const fw_cue_tone_t fw_cue_press_tones[] = {{209300u, 83u}};

static const fw_cue_t fw_cues[FW_CUE_COUNT] = {
    {fw_cue_boot_tones, 3u, 333u, 0u},
    {fw_cue_done_tones, 2u, 600u, 0u},
    {fw_cue_overheat_tones, 5u, 750u, 1u},
    {fw_cue_press_tones, 1u, 83u, 0u},
};

/* PWM frequency for `cue` after `elapsed_ms`; 0 means silence or done. */
static inline uint32_t fw_cue_centihz_at(uint8_t cue, uint32_t elapsed_ms)
{
    const fw_cue_t *c;
    uint16_t i;
    if (cue >= FW_CUE_COUNT) {
        return 0u;
    }
    c = &fw_cues[cue];
    if (elapsed_ms >= c->duration_ms) {
        if (!c->loop) {
            return 0u;
        }
        elapsed_ms %= c->duration_ms;
    }
    for (i = 0u; i < c->tone_count; i++) {
        if (elapsed_ms < c->tones[i].duration_ms) {
            return c->tones[i].centihz;
        }
        elapsed_ms -= c->tones[i].duration_ms;
    }
    return 0u;
}

#endif /* FW_CUES_H */
