/* Generated by firmware-agent from smart-kettle.fw.json; do not edit. */
#ifndef FW_PINS_H
#define FW_PINS_H

#define FW_DESIGN "smart-kettle"
#define FW_MCU_PROFILE "rp2040"

/* boil_button: GPIO2 net BTN_BOIL gpio_in */
#define FW_PIN_BOIL_BUTTON 2
#define FW_PIN_BOIL_BUTTON_PAD "GPIO2"
#define FW_PIN_BOIL_BUTTON_ACTIVE_LOW 1
#define FW_PIN_BOIL_BUTTON_PULL_UP 1
/* lid_switch: GPIO3 net LID_SW gpio_in */
#define FW_PIN_LID_SWITCH 3
#define FW_PIN_LID_SWITCH_PAD "GPIO3"
#define FW_PIN_LID_SWITCH_ACTIVE_LOW 1
#define FW_PIN_LID_SWITCH_PULL_UP 1
/* temp_sda: GPIO4 net I2C_SDA i2c_sda */
#define FW_PIN_TEMP_SDA 4
#define FW_PIN_TEMP_SDA_PAD "GPIO4"
#define FW_PIN_TEMP_SDA_ACTIVE_LOW 0
/* temp_scl: GPIO5 net I2C_SCL i2c_scl */
#define FW_PIN_TEMP_SCL 5
#define FW_PIN_TEMP_SCL_PAD "GPIO5"
#define FW_PIN_TEMP_SCL_ACTIVE_LOW 0
/* led_ring: GPIO6 net LED_RING pwm */
#define FW_PIN_LED_RING 6
#define FW_PIN_LED_RING_PAD "GPIO6"
#define FW_PIN_LED_RING_ACTIVE_LOW 0
/* heater_en: GPIO15 net HEATER_EN gpio_out */
#define FW_PIN_HEATER_EN 15
#define FW_PIN_HEATER_EN_PAD "GPIO15"
#define FW_PIN_HEATER_EN_ACTIVE_LOW 0
#define FW_PIN_HEATER_EN_INITIAL 0
/* buzzer: GPIO16 net BUZZER pwm */
#define FW_PIN_BUZZER 16
#define FW_PIN_BUZZER_PAD "GPIO16"
#define FW_PIN_BUZZER_ACTIVE_LOW 0
/* water_level: GPIO26 net WATER_LVL adc */
#define FW_PIN_WATER_LEVEL 26
#define FW_PIN_WATER_LEVEL_PAD "GPIO26"
#define FW_PIN_WATER_LEVEL_ACTIVE_LOW 0
/* debug_tx: GPIO0 net DBG_TX uart_tx */
#define FW_PIN_DEBUG_TX 0
#define FW_PIN_DEBUG_TX_PAD "GPIO0"
#define FW_PIN_DEBUG_TX_ACTIVE_LOW 0

#define FW_PERIPH_I2C_TEMP_INSTANCE 0
#define FW_PERIPH_I2C_TEMP_FREQUENCY_HZ 400000
#define FW_PERIPH_LED_PWM_INSTANCE 3
#define FW_PERIPH_BUZZER_PWM_INSTANCE 0
#define FW_PERIPH_WATER_ADC_INSTANCE 0
#define FW_PERIPH_DEBUG_UART_INSTANCE 0
#define FW_PERIPH_DEBUG_UART_BAUD 115200

#define FW_POWER_MODE_HEATING 0
#define FW_POWER_MODE_STANDBY 1
#define FW_POWER_MODE_DORMANT 2

#endif /* FW_PINS_H */
