"""Generated projections of the contract: pin header, pin map export, docs."""

from __future__ import annotations

import re
from pathlib import Path

from .contract import FirmwareContract
from .interchange import BardCueManifest, FirmwarePinmap, FreePad, PinmapEntry, ProdengFtmSpec
from .profiles import McuProfile


def _macro(value: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", value.upper()).strip("_")


def pins_header(contract: FirmwareContract, profile: McuProfile) -> str:
    lines = [
        f"/* Generated by firmware-agent from {contract.name}.fw.json; do not edit. */",
        "#ifndef FW_PINS_H",
        "#define FW_PINS_H",
        "",
        f'#define FW_DESIGN "{contract.name}"',
        f'#define FW_MCU_PROFILE "{profile.id}"',
        "",
    ]
    for pin in contract.pins:
        name = f"FW_PIN_{_macro(pin.signal)}"
        pad = profile.pad(pin.pad)
        lines.append(f"/* {pin.signal}: {pin.pad} net {pin.net} {pin.function} */")
        if pad is not None and pad.gpio is not None:
            lines.append(f"#define {name} {pad.gpio}")
        lines.append(f'#define {name}_PAD "{pin.pad}"')
        lines.append(f"#define {name}_ACTIVE_LOW {1 if pin.active == 'low' else 0}")
        if pin.pull != "none":
            lines.append(f"#define {name}_PULL_{pin.pull.upper()} 1")
        if pin.initial is not None:
            lines.append(f"#define {name}_INITIAL {1 if pin.initial == 'high' else 0}")
    if contract.peripherals:
        lines.append("")
    for peripheral in contract.peripherals:
        name = f"FW_PERIPH_{_macro(peripheral.id)}"
        lines.append(f"#define {name}_INSTANCE {peripheral.instance}")
        if peripheral.frequency_hz is not None:
            lines.append(f"#define {name}_FREQUENCY_HZ {peripheral.frequency_hz}")
        if peripheral.baud is not None:
            lines.append(f"#define {name}_BAUD {peripheral.baud}")
    lines.append("")
    for index, mode in enumerate(contract.power.modes):
        lines.append(f"#define FW_POWER_MODE_{_macro(mode.id)} {index}")
    lines += ["", "#endif /* FW_PINS_H */", ""]
    return "\n".join(lines)


def cues_header(contract: FirmwareContract, manifest: BardCueManifest, manifest_sha256: str) -> str:
    """C tone tables for the bard cue set plus a pure lookup the player calls.

    Frequencies are kept in centihertz so the 0.01 Hz manifest values survive
    exactly; ``0`` is a rest. ``fw_cue_centihz_at`` is side-effect free so a
    timer tick can map elapsed milliseconds to the PWM frequency to set.
    """
    if contract.cues is None:
        raise ValueError("contract declares no cues")
    pin_macro = f"FW_PIN_{_macro(contract.cues.pin)}"
    lines = [
        f"/* Generated by firmware-agent from {contract.name}.fw.json and bard cues.json; "
        "do not edit. */",
        "#ifndef FW_CUES_H",
        "#define FW_CUES_H",
        "",
        "#include <stdint.h>",
        "",
        f'#define FW_CUES_PRODUCT "{manifest.product}"',
        f'#define FW_CUES_DEVICE "{manifest.device}"',
        f'#define FW_CUES_SOURCE_SHA256 "{manifest_sha256}"',
        f"#define FW_CUES_PIN {pin_macro}",
        f"#define FW_CUES_MIN_CENTIHZ {round(contract.cues.min_hz * 100)}u",
        f"#define FW_CUES_MAX_CENTIHZ {round(contract.cues.max_hz * 100)}u",
        f"#define FW_CUE_COUNT {len(manifest.cues)}",
        "",
        "typedef struct {",
        "    uint32_t centihz;",
        "    uint16_t duration_ms;",
        "} fw_cue_tone_t;",
        "",
        "typedef struct {",
        "    const fw_cue_tone_t *tones;",
        "    uint16_t tone_count;",
        "    uint16_t duration_ms;",
        "    uint8_t loop;",
        "} fw_cue_t;",
        "",
    ]
    for index, cue in enumerate(manifest.cues):
        lines.append(f"#define FW_CUE_{_macro(cue.id)} {index} /* {cue.purpose} */")
    lines.append("")
    for cue in manifest.cues:
        tones = ", ".join(f"{{{round(t.freq_hz * 100)}u, {t.duration_ms}u}}" for t in cue.tones)
        lines.append(f"static const fw_cue_tone_t fw_cue_{cue.id}_tones[] = {{{tones}}};")
    lines += ["", "static const fw_cue_t fw_cues[FW_CUE_COUNT] = {"]
    for cue in manifest.cues:
        lines.append(
            f"    {{fw_cue_{cue.id}_tones, {len(cue.tones)}u, {cue.duration_ms}u, "
            f"{1 if cue.loop else 0}u}},"
        )
    lines += [
        "};",
        "",
        "/* PWM frequency for `cue` after `elapsed_ms`; 0 means silence or done. */",
        "static inline uint32_t fw_cue_centihz_at(uint8_t cue, uint32_t elapsed_ms)",
        "{",
        "    const fw_cue_t *c;",
        "    uint16_t i;",
        "    if (cue >= FW_CUE_COUNT) {",
        "        return 0u;",
        "    }",
        "    c = &fw_cues[cue];",
        "    if (elapsed_ms >= c->duration_ms) {",
        "        if (!c->loop) {",
        "            return 0u;",
        "        }",
        "        elapsed_ms %= c->duration_ms;",
        "    }",
        "    for (i = 0u; i < c->tone_count; i++) {",
        "        if (elapsed_ms < c->tones[i].duration_ms) {",
        "            return c->tones[i].centihz;",
        "        }",
        "        elapsed_ms -= c->tones[i].duration_ms;",
        "    }",
        "    return 0u;",
        "}",
        "",
        "#endif /* FW_CUES_H */",
        "",
    ]
    return "\n".join(lines)


def pinmap_export(
    contract: FirmwareContract, profile: McuProfile, contract_sha256: str
) -> FirmwarePinmap:
    entries: list[PinmapEntry] = []
    for pin in contract.pins:
        pad = profile.pad(pin.pad)
        peripheral = contract.peripheral(pin.peripheral) if pin.peripheral else None
        entries.append(
            PinmapEntry(
                signal=pin.signal,
                pad=pin.pad,
                pad_aliases=pad.aliases if pad is not None else [],
                package_pin=pin.package_pin or (pad.pin if pad is not None else None),
                net=pin.net,
                function=pin.function,
                peripheral=f"{peripheral.kind}{peripheral.instance}" if peripheral else None,
            )
        )
    used = {pin.pad for pin in contract.pins}
    free = [
        FreePad(pad=pad.name, pad_aliases=pad.aliases, package_pin=pad.pin)
        for pad in profile.pads
        if pad.reserved is None and pad.functions and pad.name not in used
    ]
    return FirmwarePinmap(
        design=contract.name,
        contract_sha256=contract_sha256,
        mcu_ref=contract.mcu.ref,
        mcu_profile=profile.id,
        mcu_part=profile.part,
        io_voltage_max_v=profile.io_voltage_max_v,
        supply_net=contract.power.supply_net,
        pins=entries,
        free_pads=free,
    )


def pinmap_markdown(pinmap: FirmwarePinmap) -> str:
    lines = [
        f"# {pinmap.design} pin map ({pinmap.mcu_part}, {pinmap.mcu_ref})",
        "",
        "Generated from the firmware contract; do not edit.",
        "",
        "| Signal | Pad | Package pin | Net | Function | Peripheral |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for entry in pinmap.pins:
        lines.append(
            f"| {entry.signal} | {entry.pad} | {entry.package_pin or '-'} | {entry.net} "
            f"| {entry.function} | {entry.peripheral or '-'} |"
        )
    return "\n".join(lines) + "\n"


def write_text(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def write_bytes(path: Path, data: bytes) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return path


def _c_string(value: str) -> str:
    if any(not " " <= char <= "~" for char in value):
        raise ValueError(f"factory test text {value!r} is not printable ASCII")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def ftm_header(contract: FirmwareContract, spec: ProdengFtmSpec, spec_sha256: str) -> str:
    """Factory test command table and entry/lockout facts from the prodeng spec."""
    if contract.ftm is None:
        raise ValueError("contract declares no ftm link")
    if not spec.commands:
        raise ValueError("factory test spec declares no commands")
    lines = [
        f"/* Generated by firmware-agent from {contract.name}.fw.json and the "
        "production-engineering factory test spec; do not edit. */",
        "#ifndef FW_FTM_H",
        "#define FW_FTM_H",
        "",
        f'#define FW_FTM_SPEC_SHA256 "{spec_sha256}"',
        f"#define FW_FTM_ENTRY {_c_string(spec.entry.method)}",
        f"#define FW_FTM_LOCKOUT {_c_string(spec.field_lockout.method)}",
        f"#define FW_FTM_TRANSPORT {_c_string(spec.interface.transport)}",
    ]
    if contract.ftm.peripheral is not None:
        lines.append(f"#define FW_FTM_PERIPH FW_PERIPH_{_macro(contract.ftm.peripheral)}_INSTANCE")
    lines += [
        f"#define FW_FTM_MAX_DURATION_MS {round(spec.max_duration_s * 1000)}u",
        f"#define FW_FTM_COMMAND_COUNT {len(spec.commands)}u",
    ]
    for item in spec.provisioning:
        once = "write once" if item.write_once else "rewritable"
        lines.append(f"#define FW_FTM_PROVISION_{_macro(item.item)} 1 /* {once} */")
    lines += [
        "",
        "typedef struct {",
        "    const char *id;",
        "    const char *request;",
        "    const char *response_pattern;",
        "    unsigned int timeout_ms;",
        "    unsigned char destructive;",
        "} fw_ftm_command_t;",
        "",
    ]
    names: set[str] = set()
    rows: list[str] = []
    for index, command in enumerate(spec.commands):
        name = f"FW_FTM_CMD_{_macro(command.name)}"
        if name in names:
            raise ValueError(f"factory test spec yields duplicate C macro {name}")
        names.add(name)
        lines.append(f"#define {name} {index}u /* {command.id} */")
        rows.append(
            f"    {{{_c_string(command.id)}, {_c_string(command.request)}, "
            f"{_c_string(command.response_pattern)}, {command.timeout_ms}u, "
            f"{1 if command.destructive else 0}u}}, \\"
        )
    lines += ["", "#define FW_FTM_COMMANDS { \\", *rows, "}", "", "#endif /* FW_FTM_H */", ""]
    return "\n".join(lines)
