"""Generated projections of the contract: pin header, pin map export, docs."""

from __future__ import annotations

import re
from pathlib import Path

from .contract import FirmwareContract
from .interchange import FirmwarePinmap, FreePad, PinmapEntry
from .profiles import McuProfile


def _macro(value: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", value.upper()).strip("_")


def pins_header(contract: FirmwareContract, profile: McuProfile) -> str:
    lines = [
        f"/* Generated by firmware-agent from {contract.name}.fw.json; do not edit. */",
        "#ifndef FW_PINS_H",
        "#define FW_PINS_H",
        "",
        f'#define FW_DESIGN "{contract.name}"',
        f'#define FW_MCU_PROFILE "{profile.id}"',
        "",
    ]
    for pin in contract.pins:
        name = f"FW_PIN_{_macro(pin.signal)}"
        pad = profile.pad(pin.pad)
        lines.append(f"/* {pin.signal}: {pin.pad} net {pin.net} {pin.function} */")
        if pad is not None and pad.gpio is not None:
            lines.append(f"#define {name} {pad.gpio}")
        lines.append(f'#define {name}_PAD "{pin.pad}"')
        lines.append(f"#define {name}_ACTIVE_LOW {1 if pin.active == 'low' else 0}")
        if pin.pull != "none":
            lines.append(f"#define {name}_PULL_{pin.pull.upper()} 1")
        if pin.initial is not None:
            lines.append(f"#define {name}_INITIAL {1 if pin.initial == 'high' else 0}")
    if contract.peripherals:
        lines.append("")
    for peripheral in contract.peripherals:
        name = f"FW_PERIPH_{_macro(peripheral.id)}"
        lines.append(f"#define {name}_INSTANCE {peripheral.instance}")
        if peripheral.frequency_hz is not None:
            lines.append(f"#define {name}_FREQUENCY_HZ {peripheral.frequency_hz}")
        if peripheral.baud is not None:
            lines.append(f"#define {name}_BAUD {peripheral.baud}")
    lines.append("")
    for index, mode in enumerate(contract.power.modes):
        lines.append(f"#define FW_POWER_MODE_{_macro(mode.id)} {index}")
    lines += ["", "#endif /* FW_PINS_H */", ""]
    return "\n".join(lines)


def pinmap_export(
    contract: FirmwareContract, profile: McuProfile, contract_sha256: str
) -> FirmwarePinmap:
    entries: list[PinmapEntry] = []
    for pin in contract.pins:
        pad = profile.pad(pin.pad)
        peripheral = contract.peripheral(pin.peripheral) if pin.peripheral else None
        entries.append(
            PinmapEntry(
                signal=pin.signal,
                pad=pin.pad,
                pad_aliases=pad.aliases if pad is not None else [],
                package_pin=pin.package_pin or (pad.pin if pad is not None else None),
                net=pin.net,
                function=pin.function,
                peripheral=f"{peripheral.kind}{peripheral.instance}" if peripheral else None,
            )
        )
    used = {pin.pad for pin in contract.pins}
    free = [
        FreePad(pad=pad.name, pad_aliases=pad.aliases, package_pin=pad.pin)
        for pad in profile.pads
        if pad.reserved is None and pad.functions and pad.name not in used
    ]
    return FirmwarePinmap(
        design=contract.name,
        contract_sha256=contract_sha256,
        mcu_ref=contract.mcu.ref,
        mcu_profile=profile.id,
        mcu_part=profile.part,
        io_voltage_max_v=profile.io_voltage_max_v,
        supply_net=contract.power.supply_net,
        pins=entries,
        free_pads=free,
    )


def pinmap_markdown(pinmap: FirmwarePinmap) -> str:
    lines = [
        f"# {pinmap.design} pin map ({pinmap.mcu_part}, {pinmap.mcu_ref})",
        "",
        "Generated from the firmware contract; do not edit.",
        "",
        "| Signal | Pad | Package pin | Net | Function | Peripheral |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for entry in pinmap.pins:
        lines.append(
            f"| {entry.signal} | {entry.pad} | {entry.package_pin or '-'} | {entry.net} "
            f"| {entry.function} | {entry.peripheral or '-'} |"
        )
    return "\n".join(lines) + "\n"


def write_text(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path
