/* Generated by firmware-agent from desk-lamp.fw.json; do not edit. */
#ifndef FW_PINS_H
#define FW_PINS_H

#define FW_DESIGN "desk-lamp"
#define FW_MCU_PROFILE "esp32s3"

/* mode_button: GPIO4 net BTN_MODE gpio_in */
#define FW_PIN_MODE_BUTTON 4
#define FW_PIN_MODE_BUTTON_PAD "GPIO4"
#define FW_PIN_MODE_BUTTON_ACTIVE_LOW 1
#define FW_PIN_MODE_BUTTON_PULL_UP 1
/* lamp_led: GPIO5 net LED_PWM pwm */
#define FW_PIN_LAMP_LED 5
#define FW_PIN_LAMP_LED_PAD "GPIO5"
#define FW_PIN_LAMP_LED_ACTIVE_LOW 0
/* debug_tx: GPIO43 net DBG_TX uart_tx */
#define FW_PIN_DEBUG_TX 43
#define FW_PIN_DEBUG_TX_PAD "GPIO43"
#define FW_PIN_DEBUG_TX_ACTIVE_LOW 0
/* debug_rx: GPIO44 net DBG_RX uart_rx */
#define FW_PIN_DEBUG_RX 44
#define FW_PIN_DEBUG_RX_PAD "GPIO44"
#define FW_PIN_DEBUG_RX_ACTIVE_LOW 0

#define FW_PERIPH_LAMP_PWM_INSTANCE 0
#define FW_PERIPH_LAMP_PWM_FREQUENCY_HZ 5000
#define FW_PERIPH_CONSOLE_INSTANCE 0
#define FW_PERIPH_CONSOLE_BAUD 115200

#define FW_POWER_MODE_LIT 0
#define FW_POWER_MODE_OFF 1

#endif /* FW_PINS_H */
